# Generated by Django 5.1.3 on 2025-01-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0007_alter_task_deadline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
